apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
        - name: genai-service
          image: spring-petclinic-microservices-main-genai-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8891
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: petclinic
spec:
  selector:
    app: genai-service
  ports:
    - port: 8891
      targetPort: 8891
