name: CI/CD - Spring Petclinic

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [config-server, discovery-server, admin-server, api-gateway, customers-service, genai-service, vets-service, visits-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
         distribution: temurin
         java-version: 17
      
      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build microservice JAR
        run: ./mvnw -pl spring-petclinic-${{ matrix.service }} clean package -DskipTests

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ steps.vars.outputs.TAG }} ./spring-petclinic-${{ matrix.service }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ steps.vars.outputs.TAG }}

      - name: Update Helm chart image tag
        run: |
          yq e -i ".${{ matrix.service }}.tag=\"${{ steps.vars.outputs.TAG }}\"" spring-petclinic/values.yaml

      - name: Commit Helm chart changes
        run: |
          git config --global user.email "phulekal@github.com"
          git config --global user.name "phulekalt"
          git add spring-petclinic/values.yaml
          if git diff --cached --quiet; then
          echo "No changes to commit"
           else
          git commit -m "Update image tag for ${{ matrix.service }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/phulekal/spring-petclinic-microservices.git HEAD:main
          fi